server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    # Aquí es donde en el futuro añadiremos la conexión al Backend
    # location /api/ {
    #    proxy_pass http://IP_PRIVADA_BACKEND:8000/;
    # }
}
